### ISSUE TITLE
Is this worth pursuing at all?

### ISSUE THREAD

**Issue by pmjones** [payload-interop/payload-interop#5]
Is an interoperable Domain Payload worth pursuing in the first place? Why, or why not?

**Comment by cherifGsoul** [comment]
How to use the Payload with the Domain? let's say that a Payload interface is implemented in a framework or in a library to communicate the UI incoming data to the application service layer, doesn't this couple the domain to an external 3rd party code?

**Comment by shochdoerfer** [comment]
I'd say it that it can make sense to be able to build reusable responders - responder classes that could potentially work with and ADR implementation out there, e.g. a JSON responder that would "convert" the domain payload into its JSON representation but also a Twig responder which would "render" the domain payload in the context of a given HTML template.

I also see a potential in standardizing action and responder interfaces as well. We had this discussion a while back and IIRC we you not really convinced that it can make sense. Maybe you want to change your mind now :P

**Comment by pavarnos** [comment]
interested to see how it looks, even just as a blog article. ADR is gaining traction.

**Comment by pmjones** [comment]
@cherifGsoul asked, "doesn't this couple the domain to an external 3rd party code?"

Yes, it would have the effect of coupling  return type of the outermost ring of the domain (Service Layer, Application Service, etc.) to 3rd-party *interface*, though not necessarily to any particular *implementation*.

@cherifGsoul Further thoughts?

(EDIT: The idea would be provide a standalone package with only the interface in it, so it could be used by anything -- no framework needed.)

**Comment by pmjones** [comment]
@shochdoerfer "I also see a potential in standardizing action and responder interfaces as well."

Maybe. One thing at a time. ;-)

**Comment by geggleto** [comment]
@pmjones The way I have been doing DDD in PHP is to expose **Services** to front-end components for READ-ONLY requirements, then to use a **Command Bus** to execute WRITE-ONLY operations in the context of a Domain.

To me this package would be an "interface/contract" on the response from Services; which I am sorta unsure I would ever need.

**Comment by cherifGsoul** [comment]
@pmjones TBH, the ```Payload``` is confusing me, is it the body of a response message (in the ADR Responder)  or the body of a request message (Command)?
I like the idea of the interface, distribute it as a ```trait``` can be an option too.

**Comment by pavarnos** [comment]
I've been using "almost ADR" in a big refactor project here. One reason for not using a Payload object is I want to type hint all the things. Will this project address that?

**Comment by pmjones** [comment]
@pavarnos "One reason for not using a Payload object is I want to type hint all the things."

/me nods

That one's tough. By its nature, a Domain Payload is likely to carry at least two things: a status of some sort ("found (or did not find) the thing(s) you asked for", "the input was invalid", "successfully created the thing(s)", etc), and the "actual" returned domain object(s) from calling a Domain element. It might carry more (e.g., the input as filtered by the domain, an error or exception object, messages about the domain activity, etc).

It means that you would typehint a Responder (or other receiver of the Payload) to the Payload, not to the domain objects within it.  This is apparently typical practice, as Payloads are coarse-grained to begin with (cf. <https://vaughnvernon.co/?page_id=40>).

You get where I'm coming from there?

**Comment by pmjones** [comment]
@cherifGsoul "the Payload is confusing me" -- see my above comment to @pavarnos , as well as <http://paul-m-jones.com/archives/6043>.

**Comment by cherifGsoul** [comment]
Thank you @pmjones

**Comment by pavarnos** [comment]
@pmjones thanks for the clear explanation. My fully type-hinted solution has a single class per action which goes out to the domain and grabs the data it needs. 
- For complex responses, there are Response Factories which return a PSR ResponseInterface directly or (as a convenience) a collection of widgets that can be rendered into a template by some shared code that returns an HtmlResponse / JsonResponse etc. 
- For simple responses, I get lazy and create the widget(s) in the action. 
I like type hinting all the way through because it makes refactoring super easy. I think a generic payload would break that?

Elsewhere you mentioned generic responders. (Can't find the reference just now). Interested to see how you'd make generic responders work with a generic payload rendered into a meaningful html UI.

**Comment by pmjones** [comment]
> My fully type-hinted solution has a single class per action which goes out to the domain and grabs the data it needs.

Nice -- do you have some examples we can look at?

**Comment by pavarnos** [comment]
@pmjones i may have been unclear: the action _is_ the single class, and a good number of type hints are just `array` or `generator` :-). So "fully type hinted" is probably a bit generous... lol.

Hard to give a realistic example without a lot of code and explanation: it's "almost ADR" and "not really DDD". Many "command" actions are a single line of code because they build on a deep class hierarchy and use a suite of traits and helper classes to pull out common code. So no Payload is needed: the parent class returns a RedirectResponse which it can calculate from the context most of the time.

A complex example is something like Project\ViewAction which renders 7 different panels describing a project (markdown), who has voted for it, what strategic initiatives it contributes to, what it depends on and blocks, what tasks are attached to it, comments by users, attached files / documents / images
```php
namespace Project;

class ViewAction {
   // ... evil constructor with 10 parameters. Haven't yet figured out how to clean that up. maybe payloads can help?

    /**
     * @param \ISV_RequestContext $context
     * @return string|\ISV\Action\Responder\PanelInterface
     */
    protected function getHtmlContent(ISV_RequestContext $context)
    {
        $project = $this->getProject($context['id']);
        $votes = $this->voteQuery->getForProject($project['id']);
        $files = $this->repository->getFileList($project['id']);
        $link  = $this->getLinkFactory($context);
        return new PanelCollection([
            new ProjectVotesPanel($link, $this->personLink, $votes, $this->getUserID()),
            new ProjectViewPanel($link, $project, $this->personLink, count($votes), $files),
            new ProjectInitiativePanel($link, $this->initiativeQuery->yieldAllForProject($project['id'])),
            new ProjectDependencyPanel($link, $this->dependencyQuery->getBlocks($project['id']),
                $this->dependencyQuery->getIsBlockedBy($project['id'])),
            new ProjectTaskPanel($link, $this->taskQuery->yieldAllForProject($project['id'])),
            new ProjectCommentsPanel($link, $this->personLink, $this->commentQuery->yieldAllForProject($project['id']),
                $this->getLastLoginTime()),
            new FileUploadPanel($link, $files),
        ]);
    }
    // blah blah support methods blah blah
}
```
Each `Panel` implements `PanelInterface`, as does `PanelCollection` which is a simple composite.
The caller can turn a PanelInterface into a string (html), push that into the template and return an HtmlResponse. It generically handles "invalid record id", "permission denied" exceptions and returns appropriate error messages / redirects.

Each panel gets as parameters
- objects (eg to render links that the user has permission to click), 
- scalars (current user ID), 
- generators / arrays with data straight from the database (no ORM). 

It returns a piece of html (nicely wrapped in `div`s). 

The Panels are easy to test: not a lot of logic in them usually
Repository / Queries are easy-ish to test: built on Aura components 
But Actions are harder to test, which is why i'm very interested to see how your Payload can take a lot of complex data to render quite a large page.
I've not built the API functionality yet, but it shouldn't be too hard: each Panel has a `->getHtml()`. Adding a `->getJSON()` doesn't feel like too much work.

I'm probably breaking a ton of rules here (for ADR, DDD, "proper OOP" and all that other good stuff). Got a lot to learn. Keen to see how generic Payloads might help break things down into more testable chunks with fewer dependencies while also making it easy to refactor. I find the more type hints I use (and the less php magic methods), the easier refactoring is. I can refactor in a few minutes what used to take days of planning and preparation. And the IDE tells me about my mistakes as I'm making them...

EDITS: fixing typos, minor clarifications

**Comment by pmjones** [comment]
@pavarnos A quick-and-dirty refactor to using a generic Payload; note the (undefined) newPayload() method that returns an (undefined ;-) Payload object:

```php
<?php
namespace Project;

class ViewAction {
   // ... constructor with 2 params: Domain\ViewProject, and some Responder

    /**
     * @param \ISV_RequestContext $context
     * @return Response HTTP response object.
     */
    protected function getHtmlContent(ISV_RequestContext $context)
    {
        $payload = $this->viewProject->get($context['id']);

        // responder then picks apart the payload to build a response:
        return $this->responder->respond($context, $payload);
    }
}

namespace Domain;

class ViewProject
{
    // constructor with 10 parameters ;-)

    public function get($id)
    {
        $project = $this->getProject($context['id']);
        if (! $project) {
            return $this->newPayload('NOT_FOUND');
        }

        $votes = $this->voteQuery->getForProject($project['id']);
        $files = $this->repository->getFileList($project['id']);
        $link  = $this->getLinkFactory($context);

        $panelCollection = new PanelCollection([
            new ProjectVotesPanel($link, $this->personLink, $votes, $this->getUserID()),
            new ProjectViewPanel($link, $project, $this->personLink, count($votes), $files),
            new ProjectInitiativePanel($link, $this->initiativeQuery->yieldAllForProject($project['id'])),
            new ProjectDependencyPanel($link, $this->dependencyQuery->getBlocks($project['id']),
                $this->dependencyQuery->getIsBlockedBy($project['id'])),
            new ProjectTaskPanel($link, $this->taskQuery->yieldAllForProject($project['id'])),
            new ProjectCommentsPanel($link, $this->personLink, $this->commentQuery->yieldAllForProject($project['id']),
                $this->getLastLoginTime()),
            new FileUploadPanel($link, $files),
        ]);

        return $this->newPayload('FOUND', [
            'panelCollection' => $panelCollection
        ]);
    }

    // blah blah support methods blah blah
}
```

Does that help illustrate the concept?

* * *

Re-reading your comment, the Panels render HTML. To make this *extra* useful, the Domain layer would only build a data structure for the project (and return that in the payload). Then the Responder can pass that data structure through a renderer of some sort. That splits up the data from the presentation.

**Comment by pavarnos** [comment]
@pmjones thanks, that does help illustrate. I still see no improvement in testability?

**Comment by niden** [comment]
Sorry to come late to the party, I just found out about this initiative.

I believe it is worth pursuing. Creating a standard implementation that would allow the transfer of data is a must IMHO. 

For a personal/work project I had implemented a Payload class but that was focused on the `Response` object so my "payload" was what was sent to the UI/client as a JSON object and not used in the context we are discussing here. 

I wanted to start implementing ADR for Phalcon and to offer it as the main pattern in v5 (currently getting ready to release v4). As such I started implementing simple components that would help with the transition and Payload was one of them. Admittedly our implementation is heavily influenced by Aura, implementing read/write interfaces.

https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Domain/Payload/Payload.zep

I would like to jump start this initiative. I believe it will be very beneficial.
